services:
  - type: web
    name: sathanic-v1
    repo: https://github.com/A-d-i-t-h-y-a-n/sathanic-bot.git
    branch: main
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: RENDER_NAME
        sync: false
        required: true
      - key: RENDER_API
        sync: false
        required: true
      - key: SESSION_ID
        sync: false
        required: true
      - key: DATABASE_URL
        sync: false
        required: true
      - key: PREFIX
        sync: false
        value: "!"
      - key: SUDO
        sync: false
        value: "admin_id_here"
      - key: MODE
        value: "private"
      - key: LOG_MSG
        value: "true"
      - key: AUTO_STATUS_VIEW
        value: "true"
      - key: READ_MSG
        value: "true"
      - key: ALWAYS_ONLINE
        value: "true"
      - key: START_MSG
        value: "true"
      - key: PORT
        value: "3000"
      - key: NODE_ENV
        value: "production"
      - key: MAX_MEMORY
        value: "512M"
